version: '3.5'

services:
  app:
    container_name: 'calculateur_cuisson'
    build: .
    ports:
      - "25000:80"
  app2:
    container_name: 'calculateur_cuisson_name'
    build: .
    ports:
      - "25001:80"