name: remote ssh command
on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build the app
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        run: pnpm
      - run: pnpm run build
